package com.itmo.collection;

import com.itmo.client.User;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * The type com.itmo.LabWork.
 */
public class LabWork implements Comparable<LabWork>, Serializable {

    private long id; //The field value must be greater than 0, must be unique, must be generated automatically
    private String name; //Field cannot be null, String cannot be empty
    private Coordinates coordinates; //Поле не может быть null
    private Date creationDate; //The field cannot be null, the value of this field must be generated automatically
    private int weight; //The field value must be greater than 0
    private float minimalpoint; //The field value must be greater than 0
    private HairColor type; //The field can be null
    private Difficulty difficulty; //The field can be null
    private Person person; //The field can be null

    @Getter @Setter
    private String ownerName;


    @Setter @Getter
    private User user;

    /**
     * Constructor with all non-autogenerated fields
     *
     * @param name        - name of LabWork
     * @param coordinates - coordinates
     * @param weight         - weight of labWork
     * @param minimalpoint    -  minimalPoint of labWork
     * @param type        - type of LabWork
     * @param difficulty   - difficulty of LabWork
     * @param person      - author of LabWork
     */
    public LabWork(String name, Coordinates coordinates, int weight, float minimalpoint,
                   HairColor type, Difficulty difficulty, Person person){
        this.name = name;
        this.coordinates = coordinates;
        this.weight = weight;
        this.minimalpoint = minimalpoint;
        this.type = type;
        this.difficulty = difficulty;
        this.person = person;
        creationDate = new Date();
    }


    public LabWork(String name, Coordinates coordinates, Date creationDate, int weight, float minimalpoint,
                   HairColor type, Difficulty difficulty, Person person){
        this.name = name;
        this.coordinates = coordinates;
        this.creationDate = creationDate;
        this.weight = weight;
        this.minimalpoint = minimalpoint;
        this.type = type;
        this.difficulty = difficulty;
        this.person = person;
    }

    /**
     *
     * @param id          the id
     * @param name        the name
     * @param coordinates the coordinates
     * @param weight         the weight
     * @param minimalpoint    the minimalPoint
     * @param type        the type
     * @param difficulty   the difficulty
     * @param person      the author
     */
    public LabWork(Long id, String name, Coordinates coordinates, int weight, float minimalpoint, HairColor type,
                   Difficulty difficulty, Person person){
        this.name = name;
        this.coordinates = coordinates;
        this.weight = weight;
        this.minimalpoint = minimalpoint;
        this.type = type;
        this.difficulty = difficulty;
        this.person = person;
        creationDate = new Date();
        this.id = id;
    }

    /**
     * Get value float.
     *
     * @return the float
     */
    public float getValue(){
        return this.minimalpoint *this.weight;
    }

    /**
     * Instantiates a new com.itmo.LabWork.
     *
     * @param name        the name
     * @param coordinates the coordinates
     * @param weight         the weight
     * @param minimalpoint    the minimalPoint
     * @param difficulty   the difficulty
     */
    public LabWork(String name, Coordinates coordinates, int weight, float minimalpoint,
                   Difficulty difficulty){
        this.name = name;
        this.coordinates = coordinates;
        this.weight = weight;
        this.minimalpoint = minimalpoint;
        this.difficulty = difficulty;
        creationDate = new Date();
    }

    /**
     * Set author.
     *
     * @param person the author
     */
    public void setPerson(Person person){
        this.person = person;
    }

    /**
     * Set type.
     *
     * @param type the type
     */
    public void setType(HairColor type){
        this.type = type;
    }

    /**
     * Gets id.
     *
     * @return the id
     */
    public long getId() {
        return id;
    }

    /**
     * Gets name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Gets coordinates.
     *
     * @return the coordinates
     */
    public Coordinates getCoordinates() {
        return coordinates;
    }

    /**
     * Gets creation date.
     *
     * @return the creation date
     */
    public Date getCreationDate() {
        return creationDate;
    }
    public String getCreatinoDateInFormat(){
        String pattern = "yyyy-MM-dd";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        return simpleDateFormat.format(creationDate);
    }

    /**
     * Gets age.
     *
     * @return the age
     */
    public int getWeight() {
        return weight;
    }

    /**
     * Gets minimalPoint.
     *
     * @return the minimalPoint
     */
    public float getMinimalpoint() {
        return minimalpoint;
    }

    /**
     * Gets type.
     *
     * @return the type
     */
    public HairColor getType() {
        return type;
    }

    /**
     * Gets difficulty.
     *
     * @return the difficulty
     */
    public Difficulty getDifficulty() {
        return difficulty;
    }

    /**
     * Gets author.
     *
     * @return the author
     */
    public Person getPerson() {
        return person;
    }
    public void setCreationDate(Date creationDate){
        this.creationDate = creationDate;
    }

    /**
     * crutch for the command updateById
     *
     * @param id id LabWork
     */
    public void setId(long id){
        this.id = id;
    }

    @Override
    public String toString() {
        return "owner: " + ownerName + "\n" +
                "id: " + this.id + "\n" +
                "name: " + this.name + "\n" +
                "coordinates: " + coordinates.getX().toString() +
                ", " + coordinates.getY() + "\n" +
                "creationDate: " + this.creationDate.toString() + "\n" +
                "weight: " + this.weight + "\n" +
                "minimal point: " + this.minimalpoint + "\n" +
                "hair color: " + ((type == null) ? "null" : this.type.toString()) + "\n" +
                "difficulty: " + this.difficulty.toString() + "\n" +
                "person: " + ((this.person == null) ? "null" : this.person.toString());
    }

    /**
     *
     * @param labWork compared labwork
     */
    @Override
    public int compareTo(LabWork labWork) {
        return Float.compare(getValue(), labWork.getValue());
    }

    public String getCreationDateInFormat(){
        String pattern = "yyyy-MM-dd";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        return simpleDateFormat.format(creationDate);
    }
}